version: '2'
services:

  postgres:
    image: postgres:9.5.2
    env_file: ./docker/.env-postgres.test

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [postgres]
    working_dir: /usr/src/app
    command: ./docker/cmd-webserver.sh
    ports: ["8001:8001"]
    env_file: ./docker/.env
    restart: "always"
